site_name: Scikit-Shapes
repo_url: https://github.com/scikit-shapes/scikit-shapes

theme:
  name: material
  features:
    - source_repository: 'https://github.com/scikit-shapes/scikit-shapes'
    - source_branch: 'main'
    - toc.follow
    - navigation.top
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

nav:
  - Home: index.md
  - Installation guide: installation.md
  - Scikit-Shapes guide: user_guide/
    # - Data:
    #   - PolyData: user_guide/data_structures/polydata.md
    #   - Images: user_guide/data_structures/images.md
    #   - What makes PolyData and Images different: user_guide/data_structures/differences.md
    # - Single Shape analysis:
    #   - MultiScaling: user_guide/single_shape/multiscale.md
    #   - Features:
    #     - Curvature: user_guide/single_shape/features/curvature.md
    # - Registration:
    #   - Registration: user_guide/registration/registration.md
    #   - Loss functions: user_guide/registration/loss.md
    #   - Deformation models: user_guide/registration/deformations.md
  - Gallery of examples: generated/gallery
  - API Reference:
    - skshapes: reference/
  - Contribution guide: contributing.md
  - About: about.md
  - License: license.md

plugins:
  - search
  - gallery:
        examples_dirs: examples          # path to your example scripts
        gallery_dirs: docs/generated/gallery
        ignore_pattern: utils*
        conf_script: docs/gallery_conf.py
  - gen-files:
      scripts:
      - docs/gen_ref_nav.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_source: true
            members_order: source
          options:
            docstring_style: numpy
            docstring_section_table: list


markdown_extensions:
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
