[project]
name = "skshapes"
version = "0.0.1"
dependencies = [
    "torch",
    "numpy",
    "pykeops",
    "geomloss",
    "jaxtyping",
    "beartype",
    "pyvista",
    "vedo",
    "fast-simplification",
]

[build-system]
requires = ["numpy", "cython", "setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 79