[project]
name = "skshapes"
version = "0.0.1"
dependencies = [
    "mkdocstrings-python",
]

[build-system]
requires = ["numpy", "cython", "setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 79