name: Python package

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:


jobs:
  build_and_test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest]
        python-version: ["3.10", "3.11"]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install package (with dependencies for linting, testing and building doc)
        run: |
          pip install --upgrade pip
          pip install -e .[dev]

      - name: Test with pytest
        run: |
          export SKSHAPES_FLOAT_DTYPE=float32
          pytest
