name: Python package

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:


jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest]
        python-version: ["3.11"]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name : Create artifacts directory
        run: |
          mkdir -p artifacts/

      - name: Install package (with dependencies for linting, testing and building doc)
        run: |
          pip install --upgrade pip
          pip install -e .[dev]

      - name: Test with pytest
        run: |
          export SKSHAPES_FLOAT_DTYPE=float32
          pytest
          cp -r htmlcov artifacts/

      # https://github.com/pyvista/setup-headless-display-action
      - name: Setup headless display
        uses: pyvista/setup-headless-display-action@v2

      # - name: build documentation
      #   if: matrix.python-version == '3.11'
      #   run: |
      #     mkdocs build
      #     cp -r site artifacts/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-py${{ matrix.python-version }}
          path: artifacts/
