# Workflow to build documentation
# On pull request: build documentation but do not publish it if docs or examples are modified
# On push to main: build documentation but do not publish it (test it)
# On release/manual trigger: build and publish documentation
name: Documentation

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'docs/**'
      - 'examples/**'
      - 'mkdocs.yml'
  workflow_dispatch:
  release:

jobs:

    build_documentation:
        name: Build Documentation
        runs-on: ubuntu-20.04

        permissions:
          deployments: write
          contents: write

        steps:
        - uses: actions/checkout@v4
        - name: Configure Git Credentials
          run: |
            git config user.name github-actions[bot]
            git config user.email 41898282+github-actions[bot]@users.noreply.github.com

        - uses: actions/setup-python@v5
          with:
            python-version: "3.11"
            cache: "pip"

        - name: Install package (with dependencies for docs)
          run: |
            pip install --upgrade pip
            pip install -r requirements_docs.txt
            pip install .

        # https://github.com/pyvista/setup-headless-display-action
        - name: Setup headless display
          uses: pyvista/setup-headless-display-action@v2

        - name: build documentation (pull request or push)
          if: github.event_name == 'pull_request' || github.event_name == 'push'
          run: mkdocs build

        - name: publish documentation (release or manual trigger)
          if: github.event_name == 'workflow_dispatch' || github.event_name == 'release'
          run: mkdocs gh-deploy --force
