name: Python package

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12"]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name : Create artifacts directory
        run: |
          mkdir -p artifacts/

      - name: syntax checking with flake8
        run: |
          pip install flake8 flake8-docstrings flake8-bugbear flake8-builtins flake8-comprehensions
          flake8 skshapes >> artifacts/flake8_report.txt
      
      - name: Install package (with dependencies)
        run: |
          pip install -e .


      - name: Test with pytest
        run: |
          pip install pytest hypothesis pytest-cov
          export SKSHAPES_FLOAT_DTYPE=float64
          pytest .
          export SKSHAPES_FLOAT_DTYPE=float32
          pytest . --cov=skshapes --cov-report=html
          cp -r htmlcov artifacts/
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-py${{ matrix.python-version }}
          path: artifacts/