# On the main test workflow, scikit-shapes is tested with all dependencies (pip install .[all])
# Here we will test the package with the minimum dependencies as well as the optional dependencies


name: Minimum_dependency_tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
    schedule:
        - cron: '0 0 * * *'
    workflow_dispatch:

jobs:
  install_and_run_tests:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install package (minimal dependencies for testing)
        run: |
          pip install --upgrade pip
          pip install -r requirements_dev.txt
          pip install .

      - name: Test with pytest
        run: |
          pytest
