# This wokflow builds and publishes the package to TestPyPI
# Trigger on: release published, manually, scheduled
# Publish only when release
# See: https://learn.scientific-python.org/development/guides/gha-wheels/
name: Wheels

on:
  workflow_dispatch:
  release:
    types:
      - published
  schedule:
    - cron: '0 0 * * *' # Every day at midnight https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07


jobs:
  dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: hynek/build-and-inspect-python-package@v2

  publish:
    needs: [dist]
    environment:
      name: TestPyPI
      url: https://test.pypi.org/p/skshapes
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: Packages
          path: dist

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
