# This wokflow builds and publishes the package to TestPyPI
# Trigger on: release published and manually
# See: https://learn.scientific-python.org/development/guides/gha-wheels/
name: Wheels

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:

  make_sdist:

    name: Make source distribution
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: build SDist
        run: pipx run build --sdist

      - name: Upload distribution
        uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz
          if-no-files-found: error

  build_wheels:

    name: Wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - uses: pypa/cibuildwheel@v2.16

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}
          path: wheelhouse/*.whl
          if-no-files-found: error


  publish-to-testpypi:

    name: Publish Python 🐍 distribution 📦 to TestPyPI
    needs: [make_sdist, build_wheels]
    environment:
      name: TestPyPI
      url: https://test.pypi.org/p/skshapes
    permissions:
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: cibw-*
          path: dist
          merge-multiple: true

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
